  TrajectoryPlannerROS:
    max_vel_x: 0.3
    min_vel_x: 0.25
    max_vel_theta: 0.5
    min_in_place_vel_theta: 0.4
    acc_lim_theta: 2.5
    acc_lim_x: 2.5
    acc_lim_y: 2.5
    holonomic_robot: false
    yaw_goal_tolerance: 0.25
    xy_goal_tolerance: 0.1
    latch_xy_goal_tolerance: true
    sim_time: 1.5
    sim_granularity: 0.025
    angular_sim_granularity: 0.05
    vx_samples: 12
    vtheta_samples: 20
    meter_scoring: true
    publish_cost_grid: true
    pdist_scale: 0.7
    gdist_scale: 0.8
    occdist_scale: 0.01
    publish_cost_grid_pc: false
