local_costmap:
    global_frame: t265_odom_frame
    robot_base_frame: t265_link
    update_frequency: 5.0
    publish_frequency: 2.0
    static_map: false
    rolling_window: true
    width: 4.0
    height: 4.0
    resolution: 0.05
    origin_x: 0
    origin_y: 0

    plugins:
        - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
        - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
